name: ace_chat
description: A Gemini-powered chatbot UI built with Flutter. Custom knowledge base, bot naming, and theme toggle support.
version: 1.0.0
homepage: https://github.com/Suneel-DK/Ace

environment:
  sdk: ^3.8.0-24.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
